refactor: move failureMode and components to introduction instead of usage
kumahq/kuma-website pull request #1267
Opened 2023-03-30 12:54 UTC by lahabana

2023-04-03 05:38 UTC, slonka requested changes
I think one section is wrong, otherwise 👍

2023-04-03 05:38 UTC, slonka commented on app/_src/production/deployment/stand-alone.md
> +## Components of a multi-zone deployment
Shouldn't this be standalone?

```suggestion
## Components of a standalone deployment
```

2023-04-03 09:49 UTC, lahabana commented on app/_src/production/deployment/stand-alone.md
> +## Components of a multi-zone deployment
Good catch :) Fixed!

2023-04-05 06:30 UTC, slonka approved these changes

2023-04-05 06:54 UTC, merged