feat(kuma-cp): added docs for tls prom secured
kumahq/kuma-website pull request #1438
Opened 2023-08-18 14:48 UTC by lukidzi

<Explain your change!>

Did you sign your commit? [Instructions](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md#sign-your-commits)

Have you read [Contributing guidelines](https://github.com/kumahq/.github/blob/main/CONTRIBUTING.md)?

2023-08-21 09:48 UTC, slonka approved these changes
Mostly nitpicks

2023-08-21 09:48 UTC, slonka commented on .github/styles/Vocab/Base/accept.txt
> + [Kk]ong
Seems not relevant

```suggestion
[Kk]ong
```

2023-08-21 09:48 UTC, slonka commented on app/_src/explore/observability.md
> +3. Outside the mesh with TLS enabled. In this case you'll need to provide certificates for each dataplane and specify configuration in the [traffic metrics configuration](/docs/{{ page.version }}/pol
```suggestion
3. Outside the mesh with TLS enabled. In this case you'll need to provide certificates for each dataplane and specify configuration in the [traffic metrics configuration](/docs/{{ page.version }}/policies/traffic-metrics#secure-metrics-with-tls). This is more secure than second option but requires more configuration.
```

2023-08-21 09:48 UTC, slonka commented on app/_src/policies/traffic-metrics.md
> +{{site.mesh_product_name}} allows configuring metrics endpoint with TLS. You can use it when the `Prometheus` deployment is outside of the mesh and requires security for the communication.
```suggestion
{{site.mesh_product_name}} allows configuring metrics endpoint with TLS. You can use it when the `Prometheus` deployment is outside of the mesh and requires secure communication.
```

2023-08-21 09:48 UTC, slonka commented on app/_src/policies/traffic-metrics.md
> +Apart from `Mesh` configuration, `kuma-sidecar` requires provided certificate and key to the `kuma-sidecar`. When the certificate and the key is available in the container, `kuma-sidecar` needs paths
```suggestion
In addition to the `Mesh` configuration, `kuma-sidecar` requires a provided certificate and key for its operation. When the certificate and key are available within the container, `kuma-sidecar` needs the paths to these files to be provided as the following environment variables:
```

2023-08-21 09:48 UTC, slonka commented on app/_src/policies/traffic-metrics.md
> +It's possible to use [`ContainerPatch`](/docs/{{ page.version }}/production/dp-config/dpp-on-kubernetes/#custom-container-configuration) to add variable into `kuma-sidecar`:
```suggestion
It's possible to use a [`ContainerPatch`](/docs/{{ page.version }}/production/dp-config/dpp-on-kubernetes/#custom-container-configuration) to add variables to `kuma-sidecar`:
```

2023-08-21 09:48 UTC, slonka commented on app/_src/policies/traffic-metrics.md
> +for `kuma-dp` with paths to them.
```suggestion
In addition to the `Mesh` configuration, `kuma-dp` requires a provided certificate and key for its operation. Please upload the certificate and the key to the machine, and then define the following environment variables with the correct paths:
* KUMA_DATAPLANE_METRICS_CERT_PATH
* KUMA_DATAPLANE_METRICS_KEY_PATH
```

2023-08-21 09:54 UTC, lahabana commented on app/_src/policies/traffic-metrics.md
>        skipMTLS: true # by default mTLS metrics are also protected by mTLS. Scraping metrics with mTLS without transparent proxy is not supported at the moment.
Only put this if lte:2.3.x right?

2023-08-21 09:55 UTC, lahabana commented on app/_src/policies/traffic-metrics.md
> +{% if_version lte:2.3.x %}
```suggestion
{% if_version gte:2.4.x %}
```

right?

2023-08-21 09:55 UTC, lahabana commented on app/_src/policies/traffic-metrics.md
> +{% if_version lte:2.3.x %}
```suggestion
{% if_version gte:2.3.x %}
```

2023-08-21 09:55 UTC, lahabana commented on app/_src/policies/traffic-metrics.md
> +{% if_version lte:2.3.x %}
```suggestion
{% if_version gte:2.4.x %}
```

2023-08-21 09:58 UTC, lahabana requested changes
This change should conditionally change all the places we refer to `skipMTLS` to recommend the new option as this is what we want to go with in the future right?

2023-08-21 13:52 UTC, lukidzi commented
> This change should conditionally change all the places we refer to `skipMTLS` to recommend the new option as this is what we want to go with in the future right?

Yes, I will apply the change to the docs, to recommend a new model since 2.4

2023-08-22 15:28 UTC, lahabana commented on app/_src/explore/observability.md
> +2. Outside the mesh. In this case you'll need to specify {% if_version lte:2.3.x %}`skipMTLS: true`{% endif_version %}{% if_version gte:2.4.x %}`tls.mode: disabled`{% endif_version %} in the [traffic
```suggestion
2. Outside the mesh. In this case you'll need to specify {% if_version lte:2.3.x %}`skipMTLS: true`{% endif_version %}{% if_version gte:2.4.x %}`tls.mode: disabled`{% endif_version %} in the [traffic metrics configuration](/docs/{{ page.version }}/policies/traffic-metrics). This is less secure but ensures Prometheus is as available as possible. It's also easier to add to an existing setup with services in and outside the mesh.
```

2023-08-22 15:30 UTC, lahabana commented on app/_src/policies/traffic-metrics.md
> +- If you disable [passthrough](/docs/{{ page.version }}/networking/non-mesh-traffic#outgoing) and your mesh uses mTLS but Prometheus is outside the mesh {% if_version lte:2.3.x %}(`skipMTLS: true`){%
```suggestion
- If you disable [passthrough](/docs/{{ page.version }}/networking/non-mesh-traffic#outgoing) and your mesh uses mTLS but Prometheus is outside the mesh {% if_version lte:2.3.x %}(`skipMTLS: true`){% endif_version %}{% if_version gte:2.4.x %}(`tls.mode: disabled`){% endif_version %} this is the only way to retrieve these metrics as the app is completely hidden behind the sidecar.
```

2023-08-22 15:31 UTC, lahabana commented on app/_src/policies/traffic-metrics.md
> +{% endif_version %}
I think this is left over

2023-08-22 16:05 UTC, lahabana approved these changes
LGTM! modulo the nits

2023-08-28 12:37 UTC, merged