remove mesh metric otel from experimental
kumahq/kuma-website pull request #2062
Opened 2024-11-04 19:16 UTC by johnharris85

Remove the `experimental` designation for OTEL in MeshMetric.

2024-11-04 19:28 UTC, Automaat approved these changes

2024-11-04 19:29 UTC, Automaat requested changes
please add `{% if_version gte:2.9.x %}` for this change so that we remove experimental only form 2.9.x version

2024-11-04 23:59 UTC, johnharris85 commented
Is 2.9 correct? Further down there is:
```
{% if_version gte:2.7.x %}
#### OpenTelemetry
...
```

Removing the 'experimental' designation from 2.7? Assuming that's correct?

2024-11-05 07:45 UTC, Automaat commented
@johnharris85 do we have `experimental` somewhere in nav bar? I cannot find it. I see that you put `gte 2.7` I think we should remove experimental only from the newest version. It was experimental in 2.7, and it had some bugs. Also, it will motivate users to use the newest version

2024-11-05 15:30 UTC, Automaat approved these changes

2024-11-05 15:36 UTC, merged