fix(*) passthrough on a Mesh update
kumahq/kuma-website pull request #293
Opened 2020-10-12 15:17 UTC by nickolaev

Signed-off-by: Nikolay Nikolaev <nikolay.nikolaev@konghq.com>

2020-10-12 22:24 UTC, austince requested changes
Small typos

2020-10-12 22:24 UTC, austince commented on docs/docs/0.7.2/policies/mesh.md
> +The passtrhough mode is enabled by default on all the dataplanes in transparent proxy mode in a Mesh. This behavior can be changed by setting the `networking.outbound.passtrhough` in the Mesh resourc
```suggestion
The passthrough mode is enabled by default on all the dataplanes in transparent proxy mode in a Mesh. This behavior can be changed by setting the `networking.outbound.passthrough` in the Mesh resource. Example:
```

2020-10-12 22:24 UTC, austince commented on docs/docs/0.7.2/policies/mesh.md
> +When `networking.outbound.passtrhough` is `false`, no traffic to any non-meh resource can leave the Mesh.
```suggestion
When `networking.outbound.passthrough` is `false`, no traffic to any non-mesh resource can leave the Mesh.
```

2020-10-13 13:49 UTC, austince approved these changes

2020-10-22 15:08 UTC, subnetmarco commented
@nickolaev this should be against `next` not `master`.

2020-11-17 03:12 UTC, merged