docs(policies) global-scoped secrets
kumahq/kuma-website pull request #375
Opened 2021-02-18 17:55 UTC by jakubdyszkiewicz

also added missing HTTP API

2021-02-23 14:28 UTC, Bradamant3 commented on docs/docs/1.0.8/security/secrets.md
> +This API requires authentication. Consult [Accessing Admin Server from a different machine](security/#user-to-control-plane-communication) how to configure remote access.
link URL needs updating to `/docs/1.0.8/security/certificates/#user-to-control-plane-communication` (yeah, my reorg, sorry about that)

2021-02-23 14:32 UTC, Bradamant3 requested changes
URL change is the only content thing. But `package-lock.json` has crept back in -- should we add this to `.gitignore`?

2021-02-24 10:40 UTC, jakubdyszkiewicz commented
Fixed links, thanks!

Reverted `package-lock.json`. We cannot ignore this file. It is essential for consistent builds
https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json

I run `yarn install` which updated various packages, but that's probably should be done in a separate PR.

2021-02-24 13:11 UTC, Bradamant3 approved these changes
LGTM

2021-02-24 15:41 UTC, merged