docs(*) add list of annotations used in k8s
kumahq/kuma-website pull request #478
Opened 2021-07-05 12:59 UTC by bartsmykla

![image](https://user-images.githubusercontent.com/11655498/124475019-87a2d200-dda1-11eb-8faf-e05adddde3e5.png)

2021-07-06 01:07 UTC, jpeach requested changes
This is great! I made some trivial copy editing suggestions.

2021-07-06 01:07 UTC, jpeach commented on docs/docs/1.2.1/documentation/overview.md
> +Metrics prometheus path to override `Mesh`-wide default path where prometheus should scrape metrics from
```suggestion
This annotation overrides the `Mesh`-wide default path where Prometheus uses to scrape metrics.
```

2021-07-06 01:07 UTC, jpeach commented on docs/docs/1.2.1/documentation/overview.md
> +Instruct sidecar to use its builtin DNS server
```suggestion
Instructs the Kuma sidecar to use its builtin DNS server.
```

2021-07-09 22:32 UTC, Bradamant3 commented
Hey Bart, I did a pretty drastic thing here and moved the whole annotations section to its own page, under a new left nav heading "Reference docs" where it now lives with the HTTP API reference. There's a link from the original page where it lived, too.

See 
https://deploy-preview-478--kuma.netlify.app/docs/1.2.1/documentation/kubernetes-annotations/
https://deploy-preview-478--kuma.netlify.app/docs/1.2.1/documentation/overview/#kubernetes-mode (scroll down a bit for the link to the new annotations page)

let me know what you think!

2021-07-13 20:06 UTC, merged