docs(dns) add extra documentation on the DNS
kumahq/kuma-website pull request #530
Opened 2021-09-09 13:06 UTC by lahabana

CoreDNS wasn't mentionned anywhere, explain how DPP DNS works
and how to update the template

Signed-off-by: Charly Molter <charly.molter@konghq.com>

2021-09-14 21:35 UTC, Bradamant3 requested changes
In addition to suggestions and inline questions, I wonder whether it might be more useful to put the `How it works` section at the top of the Data plane proxy DNS section, and then leave the `Override ...` section where it is. wdyt?

2021-09-15 16:29 UTC, lahabana commented on docs/docs/1.3.0/networking/dns.md
> +In Kuma version 1.3.0, DNS on the data plane proxy is enabled by default on Kubernetes. You can also continue to deploy with [DNS on the control plane](#control-plane-dns).
Shouldn't the wording be "Since" then?

2021-09-15 16:31 UTC, lahabana commented on docs/docs/1.3.0/networking/dns.md
> +In Kuma version 1.3.0, DNS on the data plane proxy is enabled by default on Kubernetes. You can also continue to deploy with [DNS on the control plane](#control-plane-dns).
Saw you've changed this to `As of` which is the same as Since!

2021-09-15 16:37 UTC, lahabana commented
I'm unsure about your suggestion I feel like you don't need to understand it to set it up.
You need it for advance use cases which is why it's lower down in the docs.

Otherwise I did all the updates you suggested and sorry about the future tense (bad habits die hard!)

2021-09-15 17:03 UTC, Bradamant3 approved these changes

2021-09-15 17:06 UTC, Bradamant3 commented
Heh future tense is all over the place and I'm not consistent about correcting it either. Iterate, iterate ...

Point of clarification (I might revisit in a separate PR) -- I made the suggestion to move the explanation of how DNS works up the file to avoid duplication, not to explain something users don't really need :D. So I'll go back to the file as a whole and rethink organization generally (this is a common issue throughout the docs, not limited to this page).

I'm also not seeing commits for some of the suggestions I made, but they aren't a big deal -- we can revisit another time ...

2021-09-16 07:34 UTC, lahabana commented
I took the suggestions in the general commit where other suggestions were added.

2021-09-16 07:35 UTC, merged